# Generated by Django 3.0.8 on 2020-08-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='gender',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
