# Generated by Django 3.0.8 on 2020-08-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0002_register_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='about_us',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='bloodgroup',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='designation',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
