# Generated by Django 3.0.8 on 2020-08-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0003_auto_20200807_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='bloodgroup',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
