# Generated by Django 3.0.8 on 2020-08-07 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0004_auto_20200807_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='bloodgroup',
            new_name='blood_group',
        ),
    ]
