# Generated by Django 3.0.8 on 2020-08-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0005_auto_20200807_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='about_us',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
