# Generated by Django 3.0.8 on 2020-08-07 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0006_auto_20200807_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='about_us',
            new_name='about_you',
        ),
    ]
