# Generated by Django 3.0.8 on 2020-08-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0007_auto_20200807_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='about_you',
        ),
        migrations.AddField(
            model_name='register',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
