# Generated by Django 3.0.8 on 2020-08-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0009_register_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
