# Generated by Django 3.0.8 on 2020-08-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0010_auto_20200811_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
